# ~/.config/starship.toml
# Doc: https://starship.rs/config/#prompt

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = "$all"

command_timeout = 1000 # default 500

[directory]
truncate_to_repo = false
truncation_length = 100

# Replace the "‚ùØ" symbol in the prompt with "$"
[character] # The name of the module we are configuring is "character"
error_symbol = "[$](bold red)"
success_symbol = "[$](bold green)"
